source('relis_r_lib_adminPrjt.R') # Replace this with the name of your imported library file

# The following lines consist of all the tests/plots corresponding to each category. Uncomment the required lines. 

# Descriptive statistics

# Frequency tables~Descriptive stats(Nominal variables)
# desc_distr_vector[['Transformation.Language']]
# desc_distr_vector[['Scope']]
# desc_distr_vector[['Bidirectional']]
# desc_distr_vector[['Intent']]
# desc_distr_vector[['Intent.relation']]
# desc_distr_vector[['Venue']]
# desc_distr_vector[['Search.Type']]

# Bar Plots~Descriptive stats(Nominal variables)
# bar_plot_vector[['Transformation.Language']]
# bar_plot_vector[['Scope']]
# bar_plot_vector[['Bidirectional']]
# bar_plot_vector[['Intent']]
# bar_plot_vector[['Intent.relation']]
# bar_plot_vector[['Venue']]
# bar_plot_vector[['Search.Type']]

# Statistics~Descriptive stats(Continuous variables)
# statistics_vector[['Publication.year']]

# Box Plots~Descriptive stats(Continuous variables)
# box_plot_vector[['Publication.year']]

# Violin Plots~Descriptive stats(Continuous variables)
# violin_plot_vector[['Publication.year']]

#######################################################################################

# Evolution statistics

# Frequency tables~Evolution stats(Nominal variables)
# evo_distr_vector[['Transformation.Language']]
# evo_distr_vector[['Scope']]
# evo_distr_vector[['Bidirectional']]
# evo_distr_vector[['Intent']]
# evo_distr_vector[['Intent.relation']]
# evo_distr_vector[['Venue']]
# evo_distr_vector[['Search.Type']]

# Evolution Plots~Evolution stats(Nominal variables)
# evolution_plot_vector[['Transformation.Language']]
# evolution_plot_vector[['Scope']]
# evolution_plot_vector[['Bidirectional']]
# evolution_plot_vector[['Intent']]
# evolution_plot_vector[['Intent.relation']]
# evolution_plot_vector[['Venue']]
# evolution_plot_vector[['Search.Type']]

#######################################################################################

# Comparative statistics
# Frequency Tables~Comparative stats(Nominal variables)
# comp_distr_vector[['Transformation.Language']][['Scope']]
# comp_distr_vector[['Transformation.Language']][['Bidirectional']]
# comp_distr_vector[['Transformation.Language']][['Intent']]
# comp_distr_vector[['Transformation.Language']][['Intent.relation']]
# comp_distr_vector[['Transformation.Language']][['Venue']]
# comp_distr_vector[['Transformation.Language']][['Search.Type']]
# comp_distr_vector[['Scope']][['Transformation.Language']]
# comp_distr_vector[['Scope']][['Bidirectional']]
# comp_distr_vector[['Scope']][['Intent']]
# comp_distr_vector[['Scope']][['Intent.relation']]
# comp_distr_vector[['Scope']][['Venue']]
# comp_distr_vector[['Scope']][['Search.Type']]
# comp_distr_vector[['Bidirectional']][['Transformation.Language']]
# comp_distr_vector[['Bidirectional']][['Scope']]
# comp_distr_vector[['Bidirectional']][['Intent']]
# comp_distr_vector[['Bidirectional']][['Intent.relation']]
# comp_distr_vector[['Bidirectional']][['Venue']]
# comp_distr_vector[['Bidirectional']][['Search.Type']]
# comp_distr_vector[['Intent']][['Transformation.Language']]
# comp_distr_vector[['Intent']][['Scope']]
# comp_distr_vector[['Intent']][['Bidirectional']]
# comp_distr_vector[['Intent']][['Intent.relation']]
# comp_distr_vector[['Intent']][['Venue']]
# comp_distr_vector[['Intent']][['Search.Type']]
# comp_distr_vector[['Intent.relation']][['Transformation.Language']]
# comp_distr_vector[['Intent.relation']][['Scope']]
# comp_distr_vector[['Intent.relation']][['Bidirectional']]
# comp_distr_vector[['Intent.relation']][['Intent']]
# comp_distr_vector[['Intent.relation']][['Venue']]
# comp_distr_vector[['Intent.relation']][['Search.Type']]
# comp_distr_vector[['Venue']][['Transformation.Language']]
# comp_distr_vector[['Venue']][['Scope']]
# comp_distr_vector[['Venue']][['Bidirectional']]
# comp_distr_vector[['Venue']][['Intent']]
# comp_distr_vector[['Venue']][['Intent.relation']]
# comp_distr_vector[['Venue']][['Search.Type']]
# comp_distr_vector[['Search.Type']][['Transformation.Language']]
# comp_distr_vector[['Search.Type']][['Scope']]
# comp_distr_vector[['Search.Type']][['Bidirectional']]
# comp_distr_vector[['Search.Type']][['Intent']]
# comp_distr_vector[['Search.Type']][['Intent.relation']]
# comp_distr_vector[['Search.Type']][['Venue']]

# Stacked Bar Plots~Comparative stats(Nominal variables)
# stacked_bar_plot_vector[['Transformation.Language']][['Scope']]
# stacked_bar_plot_vector[['Transformation.Language']][['Bidirectional']]
# stacked_bar_plot_vector[['Transformation.Language']][['Intent']]
# stacked_bar_plot_vector[['Transformation.Language']][['Intent.relation']]
# stacked_bar_plot_vector[['Transformation.Language']][['Venue']]
# stacked_bar_plot_vector[['Transformation.Language']][['Search.Type']]
# stacked_bar_plot_vector[['Scope']][['Transformation.Language']]
# stacked_bar_plot_vector[['Scope']][['Bidirectional']]
# stacked_bar_plot_vector[['Scope']][['Intent']]
# stacked_bar_plot_vector[['Scope']][['Intent.relation']]
# stacked_bar_plot_vector[['Scope']][['Venue']]
# stacked_bar_plot_vector[['Scope']][['Search.Type']]
# stacked_bar_plot_vector[['Bidirectional']][['Transformation.Language']]
# stacked_bar_plot_vector[['Bidirectional']][['Scope']]
# stacked_bar_plot_vector[['Bidirectional']][['Intent']]
# stacked_bar_plot_vector[['Bidirectional']][['Intent.relation']]
# stacked_bar_plot_vector[['Bidirectional']][['Venue']]
# stacked_bar_plot_vector[['Bidirectional']][['Search.Type']]
# stacked_bar_plot_vector[['Intent']][['Transformation.Language']]
# stacked_bar_plot_vector[['Intent']][['Scope']]
# stacked_bar_plot_vector[['Intent']][['Bidirectional']]
# stacked_bar_plot_vector[['Intent']][['Intent.relation']]
# stacked_bar_plot_vector[['Intent']][['Venue']]
# stacked_bar_plot_vector[['Intent']][['Search.Type']]
# stacked_bar_plot_vector[['Intent.relation']][['Transformation.Language']]
# stacked_bar_plot_vector[['Intent.relation']][['Scope']]
# stacked_bar_plot_vector[['Intent.relation']][['Bidirectional']]
# stacked_bar_plot_vector[['Intent.relation']][['Intent']]
# stacked_bar_plot_vector[['Intent.relation']][['Venue']]
# stacked_bar_plot_vector[['Intent.relation']][['Search.Type']]
# stacked_bar_plot_vector[['Venue']][['Transformation.Language']]
# stacked_bar_plot_vector[['Venue']][['Scope']]
# stacked_bar_plot_vector[['Venue']][['Bidirectional']]
# stacked_bar_plot_vector[['Venue']][['Intent']]
# stacked_bar_plot_vector[['Venue']][['Intent.relation']]
# stacked_bar_plot_vector[['Venue']][['Search.Type']]
# stacked_bar_plot_vector[['Search.Type']][['Transformation.Language']]
# stacked_bar_plot_vector[['Search.Type']][['Scope']]
# stacked_bar_plot_vector[['Search.Type']][['Bidirectional']]
# stacked_bar_plot_vector[['Search.Type']][['Intent']]
# stacked_bar_plot_vector[['Search.Type']][['Intent.relation']]
# stacked_bar_plot_vector[['Search.Type']][['Venue']]

# Grouped Bar Plots~Comparative stats(Nominal variables)
# grouped_bar_plot_vector[['Transformation.Language']][['Scope']]
# grouped_bar_plot_vector[['Transformation.Language']][['Bidirectional']]
# grouped_bar_plot_vector[['Transformation.Language']][['Intent']]
# grouped_bar_plot_vector[['Transformation.Language']][['Intent.relation']]
# grouped_bar_plot_vector[['Transformation.Language']][['Venue']]
# grouped_bar_plot_vector[['Transformation.Language']][['Search.Type']]
# grouped_bar_plot_vector[['Scope']][['Transformation.Language']]
# grouped_bar_plot_vector[['Scope']][['Bidirectional']]
# grouped_bar_plot_vector[['Scope']][['Intent']]
# grouped_bar_plot_vector[['Scope']][['Intent.relation']]
# grouped_bar_plot_vector[['Scope']][['Venue']]
# grouped_bar_plot_vector[['Scope']][['Search.Type']]
# grouped_bar_plot_vector[['Bidirectional']][['Transformation.Language']]
# grouped_bar_plot_vector[['Bidirectional']][['Scope']]
# grouped_bar_plot_vector[['Bidirectional']][['Intent']]
# grouped_bar_plot_vector[['Bidirectional']][['Intent.relation']]
# grouped_bar_plot_vector[['Bidirectional']][['Venue']]
# grouped_bar_plot_vector[['Bidirectional']][['Search.Type']]
# grouped_bar_plot_vector[['Intent']][['Transformation.Language']]
# grouped_bar_plot_vector[['Intent']][['Scope']]
# grouped_bar_plot_vector[['Intent']][['Bidirectional']]
# grouped_bar_plot_vector[['Intent']][['Intent.relation']]
# grouped_bar_plot_vector[['Intent']][['Venue']]
# grouped_bar_plot_vector[['Intent']][['Search.Type']]
# grouped_bar_plot_vector[['Intent.relation']][['Transformation.Language']]
# grouped_bar_plot_vector[['Intent.relation']][['Scope']]
# grouped_bar_plot_vector[['Intent.relation']][['Bidirectional']]
# grouped_bar_plot_vector[['Intent.relation']][['Intent']]
# grouped_bar_plot_vector[['Intent.relation']][['Venue']]
# grouped_bar_plot_vector[['Intent.relation']][['Search.Type']]
# grouped_bar_plot_vector[['Venue']][['Transformation.Language']]
# grouped_bar_plot_vector[['Venue']][['Scope']]
# grouped_bar_plot_vector[['Venue']][['Bidirectional']]
# grouped_bar_plot_vector[['Venue']][['Intent']]
# grouped_bar_plot_vector[['Venue']][['Intent.relation']]
# grouped_bar_plot_vector[['Venue']][['Search.Type']]
# grouped_bar_plot_vector[['Search.Type']][['Transformation.Language']]
# grouped_bar_plot_vector[['Search.Type']][['Scope']]
# grouped_bar_plot_vector[['Search.Type']][['Bidirectional']]
# grouped_bar_plot_vector[['Search.Type']][['Intent']]
# grouped_bar_plot_vector[['Search.Type']][['Intent.relation']]
# grouped_bar_plot_vector[['Search.Type']][['Venue']]

# Bubble Charts~Comparative stats(Nominal variables)
# bubble_chart_vector[['Transformation.Language']][['Scope']]
# bubble_chart_vector[['Transformation.Language']][['Bidirectional']]
# bubble_chart_vector[['Transformation.Language']][['Intent']]
# bubble_chart_vector[['Transformation.Language']][['Intent.relation']]
# bubble_chart_vector[['Transformation.Language']][['Venue']]
# bubble_chart_vector[['Transformation.Language']][['Search.Type']]
# bubble_chart_vector[['Scope']][['Transformation.Language']]
# bubble_chart_vector[['Scope']][['Bidirectional']]
# bubble_chart_vector[['Scope']][['Intent']]
# bubble_chart_vector[['Scope']][['Intent.relation']]
# bubble_chart_vector[['Scope']][['Venue']]
# bubble_chart_vector[['Scope']][['Search.Type']]
# bubble_chart_vector[['Bidirectional']][['Transformation.Language']]
# bubble_chart_vector[['Bidirectional']][['Scope']]
# bubble_chart_vector[['Bidirectional']][['Intent']]
# bubble_chart_vector[['Bidirectional']][['Intent.relation']]
# bubble_chart_vector[['Bidirectional']][['Venue']]
# bubble_chart_vector[['Bidirectional']][['Search.Type']]
# bubble_chart_vector[['Intent']][['Transformation.Language']]
# bubble_chart_vector[['Intent']][['Scope']]
# bubble_chart_vector[['Intent']][['Bidirectional']]
# bubble_chart_vector[['Intent']][['Intent.relation']]
# bubble_chart_vector[['Intent']][['Venue']]
# bubble_chart_vector[['Intent']][['Search.Type']]
# bubble_chart_vector[['Intent.relation']][['Transformation.Language']]
# bubble_chart_vector[['Intent.relation']][['Scope']]
# bubble_chart_vector[['Intent.relation']][['Bidirectional']]
# bubble_chart_vector[['Intent.relation']][['Intent']]
# bubble_chart_vector[['Intent.relation']][['Venue']]
# bubble_chart_vector[['Intent.relation']][['Search.Type']]
# bubble_chart_vector[['Venue']][['Transformation.Language']]
# bubble_chart_vector[['Venue']][['Scope']]
# bubble_chart_vector[['Venue']][['Bidirectional']]
# bubble_chart_vector[['Venue']][['Intent']]
# bubble_chart_vector[['Venue']][['Intent.relation']]
# bubble_chart_vector[['Venue']][['Search.Type']]
# bubble_chart_vector[['Search.Type']][['Transformation.Language']]
# bubble_chart_vector[['Search.Type']][['Scope']]
# bubble_chart_vector[['Search.Type']][['Bidirectional']]
# bubble_chart_vector[['Search.Type']][['Intent']]
# bubble_chart_vector[['Search.Type']][['Intent.relation']]
# bubble_chart_vector[['Search.Type']][['Venue']]

# Fisher's Exact Test~Comparative stats(Nominal variables)
# fisher_exact_test_vector[['Transformation.Language']][['Scope']]
# fisher_exact_test_vector[['Transformation.Language']][['Bidirectional']]
# fisher_exact_test_vector[['Transformation.Language']][['Intent']]
# fisher_exact_test_vector[['Transformation.Language']][['Intent.relation']]
# fisher_exact_test_vector[['Transformation.Language']][['Venue']]
# fisher_exact_test_vector[['Transformation.Language']][['Search.Type']]
# fisher_exact_test_vector[['Scope']][['Transformation.Language']]
# fisher_exact_test_vector[['Scope']][['Bidirectional']]
# fisher_exact_test_vector[['Scope']][['Intent']]
# fisher_exact_test_vector[['Scope']][['Intent.relation']]
# fisher_exact_test_vector[['Scope']][['Venue']]
# fisher_exact_test_vector[['Scope']][['Search.Type']]
# fisher_exact_test_vector[['Bidirectional']][['Transformation.Language']]
# fisher_exact_test_vector[['Bidirectional']][['Scope']]
# fisher_exact_test_vector[['Bidirectional']][['Intent']]
# fisher_exact_test_vector[['Bidirectional']][['Intent.relation']]
# fisher_exact_test_vector[['Bidirectional']][['Venue']]
# fisher_exact_test_vector[['Bidirectional']][['Search.Type']]
# fisher_exact_test_vector[['Intent']][['Transformation.Language']]
# fisher_exact_test_vector[['Intent']][['Scope']]
# fisher_exact_test_vector[['Intent']][['Bidirectional']]
# fisher_exact_test_vector[['Intent']][['Intent.relation']]
# fisher_exact_test_vector[['Intent']][['Venue']]
# fisher_exact_test_vector[['Intent']][['Search.Type']]
# fisher_exact_test_vector[['Intent.relation']][['Transformation.Language']]
# fisher_exact_test_vector[['Intent.relation']][['Scope']]
# fisher_exact_test_vector[['Intent.relation']][['Bidirectional']]
# fisher_exact_test_vector[['Intent.relation']][['Intent']]
# fisher_exact_test_vector[['Intent.relation']][['Venue']]
# fisher_exact_test_vector[['Intent.relation']][['Search.Type']]
# fisher_exact_test_vector[['Venue']][['Transformation.Language']]
# fisher_exact_test_vector[['Venue']][['Scope']]
# fisher_exact_test_vector[['Venue']][['Bidirectional']]
# fisher_exact_test_vector[['Venue']][['Intent']]
# fisher_exact_test_vector[['Venue']][['Intent.relation']]
# fisher_exact_test_vector[['Venue']][['Search.Type']]
# fisher_exact_test_vector[['Search.Type']][['Transformation.Language']]
# fisher_exact_test_vector[['Search.Type']][['Scope']]
# fisher_exact_test_vector[['Search.Type']][['Bidirectional']]
# fisher_exact_test_vector[['Search.Type']][['Intent']]
# fisher_exact_test_vector[['Search.Type']][['Intent.relation']]
# fisher_exact_test_vector[['Search.Type']][['Venue']]

# Shapiro Wilk's Correlation Test~Comparative stats(Continuous variables)
# shapiro_wilk_test_vector[['Publication.year']]

# Pearson's Correlation Test~Comparative stats(Continuous variables)

# Spearman's Correlation Test~Comparative stats(Continuous variables)

#######################################################################################