services:
  db:
    container_name: relis-db
    image: mariadb:11.4
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      
    volumes:
      - ./db/initial_db.sql:/docker-entrypoint-initdb.d/initial_db.sql
      - ../data/db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - ./db/config.inc.php:/etc/phpmyadmin/config.inc.php
      - ../:/u/relis/public_html

  tomcat:
    depends_on:
      - db
    build:
      context: ./tomcat/
    volumes:
      - ../data/tomcat_data:/u/relis/public_html/workspace
      - ./tomcat/testfiles/classification_install_demoTestProject.php:/u/relis/public_html/workspace/dslforge_workspace/tests/src-gen/classification_install_demoTestProject.php
      - ./tomcat/testfiles/classification_install_demoTestProject.pdf:/u/relis/public_html/workspace/dslforge_workspace/tests/src-gen/classification_install_demoTestProject.pdf
      - ./tomcat/testfiles/classification_install_demoTestProject2.php:/u/relis/public_html/workspace/dslforge_workspace/tests/src-gen/classification_install_demoTestProject2.php
      - ./tomcat/demofiles/classification_install_demo_relis.php:/u/relis/public_html/workspace/dslforge_workspace/demo_relis/src-gen/classification_install_demo_relis.php

    environment:
      MYSQL_DATABASE: db
      CATALINA_OPTS: '-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
      JAVA_OPTS: '-Djava.security.egd=file:///dev/urandom'
    ports:
      - 8088:8080
      - 8089:8181

  bibler:
    container_name: bibler
    image: relis/bibler
    restart: always
    networks:
      default:
        aliases:
          - relisbibler

  relis-application:
    depends_on:
      - db
    container_name: relis-app
    build:
      context: ./
      args:
        DIRECTORY_INDEX: index.php
        DOCUMENT_ROOT: /u/relis/public_html
        ENV: dev
    env_file:
      - .env
    entrypoint: /usr/local/bin/entrypoint.sh
    ports:
      - 8083:80
    volumes:
      - ../:/u/relis/public_html
    extra_hosts:
      - "host.docker.internal:host-gateway"
