<?php
/* ReLiS - A Tool for conducting systematic literature reviews and mapping studies.
 * Copyright (C) 2018  Eugene Syriani
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 * 
 * --------------------------------------------------------------------------
 * 
 *  :Author: LLM Integration Team
 */

defined('BASEPATH') or exit('No direct script access allowed');

/**
 * Inclusion Criteria Configuration
 * Custom configuration for ref_inclusioncriteria table with LLM category field
 */
function get_inclusion_criteria_config() {
    $config = array();
    
    $config['config_id'] = 'inclusioncriteria';
    $config['table_name'] = 'ref_inclusioncriteria';
    $config['table_id'] = 'ref_id';
    $config['table_active_field'] = 'ref_active';
    $config['main_field'] = 'ref_value';
    
    $config['entity_label'] = 'Inclusion Criteria';
    $config['entity_label_plural'] = 'Inclusion Criteria';
    
    // List view configuration
    $config['order_by'] = 'ref_value ASC';
    $config['search_by'] = 'ref_value, ref_desc';
    
    // Define fields
    $fields = array();
    
    $fields['ref_id'] = array(
        'field_title' => '#',
        'field_type' => 'int',
        'field_size' => 11,
        'field_value' => 'auto_increment',
        'default_value' => 'auto_increment',
        'on_add' => 'hidden',
        'on_edit' => 'hidden'
    );
    
    $fields['ref_value'] = array(
        'field_title' => 'Inclusion Criteria',
        'field_type' => 'text',
        'field_size' => 100,
        'input_type' => 'text',
        'mandatory' => ' mandatory ',
        'on_add' => 'enabled',
        'on_edit' => 'enabled'
    );
    
    $fields['ref_desc'] = array(
        'field_title' => 'Description',
        'field_type' => 'text',
        'field_size' => 1000,
        'input_type' => 'textarea',
        'on_add' => 'enabled',
        'on_edit' => 'enabled'
    );
    
    $fields['criteria_category'] = array(
        'field_title' => 'Category',
        'field_type' => 'enum',
        'field_size' => 20,
        'input_type' => 'select',
        'input_select_source' => 'array',
        'input_select_values' => array(
            'topic_relevance' => 'Topic Relevance',
            'type_of_study' => 'Type of Study',
            'quality_of_study' => 'Quality of Study'
        ),
        'default_value' => 'topic_relevance',
        'field_desc' => 'Category for organizing criteria in LLM prompts',
        'on_add' => 'enabled',
        'on_edit' => 'enabled'
    );
    
    $fields['inclusion_question'] = array(
        'field_title' => 'Generated Question',
        'field_type' => 'text',
        'field_size' => 1000,
        'input_type' => 'textarea',
        'field_desc' => 'LLM-generated question for this inclusion criteria',
        'on_add' => 'disabled',
        'on_edit' => 'enabled'
    );
    
    $fields['question_generated_time'] = array(
        'field_title' => 'Question Generated',
        'field_type' => 'datetime',
        'field_size' => 20,
        'input_type' => 'text',
        'field_desc' => 'When the question was generated by LLM',
        'on_add' => 'hidden',
        'on_edit' => 'hidden'
    );
    
    $fields['question_generated_by_llm'] = array(
        'field_title' => 'Generated by LLM',
        'field_type' => 'int',
        'field_size' => 11,
        'input_type' => 'text',
        'field_desc' => 'LLM configuration ID used to generate the question',
        'on_add' => 'hidden',
        'on_edit' => 'hidden'
    );
    
    $fields['ref_active'] = array(
        'field_title' => 'Active',
        'field_type' => 'int',
        'field_size' => '1',
        'field_value' => '1',
        'default_value' => '1',
        'on_add' => 'hidden',
        'on_edit' => 'hidden'
    );
    
    $config['fields'] = $fields;
    
    // Operations configuration
    $operations = array();
    
    // List operation
    $operations['list_inclusioncriteria'] = array(
        'operation_type' => 'List',
        'operation_title' => 'List of Inclusion Criteria',
        'operation_description' => 'List of Inclusion Criteria',
        'page_title' => 'List of Inclusion Criteria',
        'data_source' => 'get_list_inclusioncriteria',
        'generate_stored_procedure' => True,
        'fields' => array(
            'ref_value' => array(
                'link' => array(
                    'url' => 'element/edit_element/edit_inclusioncriteria/',
                    'id_field' => 'ref_id',
                    'trim' => '0'
                )
            ),
            'criteria_category' => array(),
            'ref_desc' => array(),
            'inclusion_question' => array()
        ),
        'order_by' => 'ref_value ASC',
        'search_by' => 'ref_value, ref_desc',
        'list_links' => array(
            'edit' => array(
                'label' => 'Edit',
                'title' => 'Edit',
                'icon' => 'edit',
                'url' => 'element/edit_element/edit_inclusioncriteria/',
            ),
            'delete' => array(
                'label' => 'Delete',
                'title' => 'Delete the inclusion criteria',
                'icon' => 'trash',
                'url' => 'element/delete_element/remove_inclusioncriteria/'
            )
        ),
        'top_links' => array(
            'add' => array(
                'label' => '',
                'title' => 'Add Inclusion Criteria',
                'icon' => 'add',
                'url' => 'element/add_element/add_inclusioncriteria',
            ),
            'generate_questions' => array(
                'label' => '',
                'title' => 'Generate Questions',
                'icon' => 'magic',
                'url' => '#',
                'onclick' => 'openGenerateQuestionsModal("inclusion")',
            ),
            'back' => array(
                'label' => '',
                'title' => 'Back',
                'icon' => 'back',
                'url' => 'screening/screening_select',
            )
        )
    );
    
    // Add operation
    $operations['add_inclusioncriteria'] = array(
        'operation_type' => 'Add',
        'operation_title' => 'Add Inclusion Criteria',
        'operation_description' => 'Add a new inclusion criteria',
        'page_title' => 'Add Inclusion Criteria',
        'save_function' => 'element/save_element',
        'page_template' => 'general/frm_entity',
        'redirect_after_save' => 'element/entity_list/list_inclusioncriteria',
        'db_save_model' => 'add_inclusioncriteria',
        'generate_stored_procedure' => True,
        'fields' => array(
            'ref_value' => array('mandatory' => 'mandatory', 'field_state' => 'enabled'),
            'ref_desc' => array('mandatory' => '', 'field_state' => 'enabled'),
            'criteria_category' => array('mandatory' => '', 'field_state' => 'enabled'),
            'inclusion_question' => array('mandatory' => '', 'field_state' => 'hidden')
        ),
        'top_links' => array(
            'back' => array(
                'label' => '',
                'title' => 'Back',
                'icon' => 'back',
                'url' => 'element/entity_list/list_inclusioncriteria',
            )
        )
    );
    
    // Edit operation
    $operations['edit_inclusioncriteria'] = array(
        'operation_type' => 'Edit',
        'operation_title' => 'Edit Inclusion Criteria',
        'operation_description' => 'Edit an existing inclusion criteria',
        'page_title' => 'Edit Inclusion Criteria',
        'save_function' => 'element/save_element',
        'page_template' => 'general/frm_entity',
        'redirect_after_save' => 'element/entity_list/list_inclusioncriteria',
        'data_source' => 'get_detail_inclusioncriteria',
        'db_save_model' => 'update_inclusioncriteria',
        'generate_stored_procedure' => True,
        'fields' => array(
            'ref_id' => array('mandatory' => '', 'field_state' => 'hidden'),
            'ref_value' => array('mandatory' => 'mandatory', 'field_state' => 'enabled'),
            'ref_desc' => array('mandatory' => '', 'field_state' => 'enabled'),
            'criteria_category' => array('mandatory' => '', 'field_state' => 'enabled'),
            'inclusion_question' => array('mandatory' => '', 'field_state' => 'enabled')
        ),
        'top_links' => array(
            'back' => array(
                'label' => '',
                'title' => 'Back',
                'icon' => 'back',
                'url' => 'element/entity_list/list_inclusioncriteria',
            )
        )
    );
    
    // Detail operation
    $operations['detail_inclusioncriteria'] = array(
        'operation_type' => 'Detail',
        'operation_title' => 'Inclusion Criteria Details',
        'operation_description' => 'View inclusion criteria details',
        'page_title' => 'Inclusion Criteria Details',
        'data_source' => 'get_detail_inclusioncriteria',
        'generate_stored_procedure' => True,
        'generate_stored_procedure' => True,
        'fields' => array(
            'ref_value' => array(),
            'ref_desc' => array(),
            'criteria_category' => array(),
            'inclusion_question' => array()
        ),
        'top_links' => array(
            'back' => array(
                'label' => '',
                'title' => 'Back',
                'icon' => 'back',
                'url' => 'element/entity_list/list_inclusioncriteria',
            )
        )
    );
    
    // Remove operation
    $operations['remove_inclusioncriteria'] = array(
        'operation_type' => 'Remove',
        'operation_title' => 'Remove Inclusion Criteria',
        'operation_description' => 'Remove an inclusion criteria',
        'page_title' => 'Remove Inclusion Criteria',
        'data_source' => 'get_remove_inclusioncriteria',
        'save_function' => 'element/save_element',
        'redirect_after_save' => 'element/entity_list/list_inclusioncriteria',
        'db_save_model' => 'remove_inclusioncriteria',
        'db_delete_model' => 'remove_inclusioncriteria',
        'generate_stored_procedure' => True,
        'top_links' => array(
            'back' => array(
                'label' => '',
                'title' => 'Back',
                'icon' => 'back',
                'url' => 'element/entity_list/list_inclusioncriteria',
            )
        )
    );
    
    $config['operations'] = $operations;
    
    return $config;
}





