source('relis_r_lib_demoTestProject.R') # Replace this with the name of your imported library file

# The following lines consist of all the tests/plots corresponding to each category. Uncomment the required lines. 

# Descriptive statistics

# Frequency tables~Descriptive stats(Nominal variables)
# desc_distr_vector[['Has.chocolate']]
# desc_distr_vector[['Brand']]
# desc_distr_vector[['Cocoa.origin']]
# desc_distr_vector[['Cocoa.level']]
# desc_distr_vector[['Types']]
# desc_distr_vector[['Variety']]
# desc_distr_vector[['Venue']]
# desc_distr_vector[['Search.Type']]

# Bar Plots~Descriptive stats(Nominal variables)
# bar_plot_vector[['Has.chocolate']]
# bar_plot_vector[['Brand']]
# bar_plot_vector[['Cocoa.origin']]
# bar_plot_vector[['Cocoa.level']]
# bar_plot_vector[['Types']]
# bar_plot_vector[['Variety']]
# bar_plot_vector[['Venue']]
# bar_plot_vector[['Search.Type']]

# Statistics~Descriptive stats(Continuous variables)
# statistics_vector[['Temperature']]
# statistics_vector[['Year']]
# statistics_vector[['Number.of.citations']]
# statistics_vector[['Publication.year']]

# Box Plots~Descriptive stats(Continuous variables)
# box_plot_vector[['Temperature']]
# box_plot_vector[['Year']]
# box_plot_vector[['Number.of.citations']]
# box_plot_vector[['Publication.year']]

# Violin Plots~Descriptive stats(Continuous variables)
# violin_plot_vector[['Temperature']]
# violin_plot_vector[['Year']]
# violin_plot_vector[['Number.of.citations']]
# violin_plot_vector[['Publication.year']]

#######################################################################################

# Evolution statistics

# Frequency tables~Evolution stats(Nominal variables)
# evo_distr_vector[['Has.chocolate']]
# evo_distr_vector[['Brand']]
# evo_distr_vector[['Cocoa.origin']]
# evo_distr_vector[['Cocoa.level']]
# evo_distr_vector[['Types']]
# evo_distr_vector[['Variety']]
# evo_distr_vector[['Venue']]
# evo_distr_vector[['Search.Type']]

# Evolution Plots~Evolution stats(Nominal variables)
# evolution_plot_vector[['Has.chocolate']]
# evolution_plot_vector[['Brand']]
# evolution_plot_vector[['Cocoa.origin']]
# evolution_plot_vector[['Cocoa.level']]
# evolution_plot_vector[['Types']]
# evolution_plot_vector[['Variety']]
# evolution_plot_vector[['Venue']]
# evolution_plot_vector[['Search.Type']]

#######################################################################################

# Comparative statistics
# Frequency Tables~Comparative stats(Nominal variables)
# comp_distr_vector[['Has.chocolate']][['Brand']]
# comp_distr_vector[['Has.chocolate']][['Cocoa.origin']]
# comp_distr_vector[['Has.chocolate']][['Cocoa.level']]
# comp_distr_vector[['Has.chocolate']][['Types']]
# comp_distr_vector[['Has.chocolate']][['Variety']]
# comp_distr_vector[['Has.chocolate']][['Venue']]
# comp_distr_vector[['Has.chocolate']][['Search.Type']]
# comp_distr_vector[['Brand']][['Has.chocolate']]
# comp_distr_vector[['Brand']][['Cocoa.origin']]
# comp_distr_vector[['Brand']][['Cocoa.level']]
# comp_distr_vector[['Brand']][['Types']]
# comp_distr_vector[['Brand']][['Variety']]
# comp_distr_vector[['Brand']][['Venue']]
# comp_distr_vector[['Brand']][['Search.Type']]
# comp_distr_vector[['Cocoa.origin']][['Has.chocolate']]
# comp_distr_vector[['Cocoa.origin']][['Brand']]
# comp_distr_vector[['Cocoa.origin']][['Cocoa.level']]
# comp_distr_vector[['Cocoa.origin']][['Types']]
# comp_distr_vector[['Cocoa.origin']][['Variety']]
# comp_distr_vector[['Cocoa.origin']][['Venue']]
# comp_distr_vector[['Cocoa.origin']][['Search.Type']]
# comp_distr_vector[['Cocoa.level']][['Has.chocolate']]
# comp_distr_vector[['Cocoa.level']][['Brand']]
# comp_distr_vector[['Cocoa.level']][['Cocoa.origin']]
# comp_distr_vector[['Cocoa.level']][['Types']]
# comp_distr_vector[['Cocoa.level']][['Variety']]
# comp_distr_vector[['Cocoa.level']][['Venue']]
# comp_distr_vector[['Cocoa.level']][['Search.Type']]
# comp_distr_vector[['Types']][['Has.chocolate']]
# comp_distr_vector[['Types']][['Brand']]
# comp_distr_vector[['Types']][['Cocoa.origin']]
# comp_distr_vector[['Types']][['Cocoa.level']]
# comp_distr_vector[['Types']][['Variety']]
# comp_distr_vector[['Types']][['Venue']]
# comp_distr_vector[['Types']][['Search.Type']]
# comp_distr_vector[['Variety']][['Has.chocolate']]
# comp_distr_vector[['Variety']][['Brand']]
# comp_distr_vector[['Variety']][['Cocoa.origin']]
# comp_distr_vector[['Variety']][['Cocoa.level']]
# comp_distr_vector[['Variety']][['Types']]
# comp_distr_vector[['Variety']][['Venue']]
# comp_distr_vector[['Variety']][['Search.Type']]
# comp_distr_vector[['Venue']][['Has.chocolate']]
# comp_distr_vector[['Venue']][['Brand']]
# comp_distr_vector[['Venue']][['Cocoa.origin']]
# comp_distr_vector[['Venue']][['Cocoa.level']]
# comp_distr_vector[['Venue']][['Types']]
# comp_distr_vector[['Venue']][['Variety']]
# comp_distr_vector[['Venue']][['Search.Type']]
# comp_distr_vector[['Search.Type']][['Has.chocolate']]
# comp_distr_vector[['Search.Type']][['Brand']]
# comp_distr_vector[['Search.Type']][['Cocoa.origin']]
# comp_distr_vector[['Search.Type']][['Cocoa.level']]
# comp_distr_vector[['Search.Type']][['Types']]
# comp_distr_vector[['Search.Type']][['Variety']]
# comp_distr_vector[['Search.Type']][['Venue']]

# Stacked Bar Plots~Comparative stats(Nominal variables)
# stacked_bar_plot_vector[['Has.chocolate']][['Brand']]
# stacked_bar_plot_vector[['Has.chocolate']][['Cocoa.origin']]
# stacked_bar_plot_vector[['Has.chocolate']][['Cocoa.level']]
# stacked_bar_plot_vector[['Has.chocolate']][['Types']]
# stacked_bar_plot_vector[['Has.chocolate']][['Variety']]
# stacked_bar_plot_vector[['Has.chocolate']][['Venue']]
# stacked_bar_plot_vector[['Has.chocolate']][['Search.Type']]
# stacked_bar_plot_vector[['Brand']][['Has.chocolate']]
# stacked_bar_plot_vector[['Brand']][['Cocoa.origin']]
# stacked_bar_plot_vector[['Brand']][['Cocoa.level']]
# stacked_bar_plot_vector[['Brand']][['Types']]
# stacked_bar_plot_vector[['Brand']][['Variety']]
# stacked_bar_plot_vector[['Brand']][['Venue']]
# stacked_bar_plot_vector[['Brand']][['Search.Type']]
# stacked_bar_plot_vector[['Cocoa.origin']][['Has.chocolate']]
# stacked_bar_plot_vector[['Cocoa.origin']][['Brand']]
# stacked_bar_plot_vector[['Cocoa.origin']][['Cocoa.level']]
# stacked_bar_plot_vector[['Cocoa.origin']][['Types']]
# stacked_bar_plot_vector[['Cocoa.origin']][['Variety']]
# stacked_bar_plot_vector[['Cocoa.origin']][['Venue']]
# stacked_bar_plot_vector[['Cocoa.origin']][['Search.Type']]
# stacked_bar_plot_vector[['Cocoa.level']][['Has.chocolate']]
# stacked_bar_plot_vector[['Cocoa.level']][['Brand']]
# stacked_bar_plot_vector[['Cocoa.level']][['Cocoa.origin']]
# stacked_bar_plot_vector[['Cocoa.level']][['Types']]
# stacked_bar_plot_vector[['Cocoa.level']][['Variety']]
# stacked_bar_plot_vector[['Cocoa.level']][['Venue']]
# stacked_bar_plot_vector[['Cocoa.level']][['Search.Type']]
# stacked_bar_plot_vector[['Types']][['Has.chocolate']]
# stacked_bar_plot_vector[['Types']][['Brand']]
# stacked_bar_plot_vector[['Types']][['Cocoa.origin']]
# stacked_bar_plot_vector[['Types']][['Cocoa.level']]
# stacked_bar_plot_vector[['Types']][['Variety']]
# stacked_bar_plot_vector[['Types']][['Venue']]
# stacked_bar_plot_vector[['Types']][['Search.Type']]
# stacked_bar_plot_vector[['Variety']][['Has.chocolate']]
# stacked_bar_plot_vector[['Variety']][['Brand']]
# stacked_bar_plot_vector[['Variety']][['Cocoa.origin']]
# stacked_bar_plot_vector[['Variety']][['Cocoa.level']]
# stacked_bar_plot_vector[['Variety']][['Types']]
# stacked_bar_plot_vector[['Variety']][['Venue']]
# stacked_bar_plot_vector[['Variety']][['Search.Type']]
# stacked_bar_plot_vector[['Venue']][['Has.chocolate']]
# stacked_bar_plot_vector[['Venue']][['Brand']]
# stacked_bar_plot_vector[['Venue']][['Cocoa.origin']]
# stacked_bar_plot_vector[['Venue']][['Cocoa.level']]
# stacked_bar_plot_vector[['Venue']][['Types']]
# stacked_bar_plot_vector[['Venue']][['Variety']]
# stacked_bar_plot_vector[['Venue']][['Search.Type']]
# stacked_bar_plot_vector[['Search.Type']][['Has.chocolate']]
# stacked_bar_plot_vector[['Search.Type']][['Brand']]
# stacked_bar_plot_vector[['Search.Type']][['Cocoa.origin']]
# stacked_bar_plot_vector[['Search.Type']][['Cocoa.level']]
# stacked_bar_plot_vector[['Search.Type']][['Types']]
# stacked_bar_plot_vector[['Search.Type']][['Variety']]
# stacked_bar_plot_vector[['Search.Type']][['Venue']]

# Grouped Bar Plots~Comparative stats(Nominal variables)
# grouped_bar_plot_vector[['Has.chocolate']][['Brand']]
# grouped_bar_plot_vector[['Has.chocolate']][['Cocoa.origin']]
# grouped_bar_plot_vector[['Has.chocolate']][['Cocoa.level']]
# grouped_bar_plot_vector[['Has.chocolate']][['Types']]
# grouped_bar_plot_vector[['Has.chocolate']][['Variety']]
# grouped_bar_plot_vector[['Has.chocolate']][['Venue']]
# grouped_bar_plot_vector[['Has.chocolate']][['Search.Type']]
# grouped_bar_plot_vector[['Brand']][['Has.chocolate']]
# grouped_bar_plot_vector[['Brand']][['Cocoa.origin']]
# grouped_bar_plot_vector[['Brand']][['Cocoa.level']]
# grouped_bar_plot_vector[['Brand']][['Types']]
# grouped_bar_plot_vector[['Brand']][['Variety']]
# grouped_bar_plot_vector[['Brand']][['Venue']]
# grouped_bar_plot_vector[['Brand']][['Search.Type']]
# grouped_bar_plot_vector[['Cocoa.origin']][['Has.chocolate']]
# grouped_bar_plot_vector[['Cocoa.origin']][['Brand']]
# grouped_bar_plot_vector[['Cocoa.origin']][['Cocoa.level']]
# grouped_bar_plot_vector[['Cocoa.origin']][['Types']]
# grouped_bar_plot_vector[['Cocoa.origin']][['Variety']]
# grouped_bar_plot_vector[['Cocoa.origin']][['Venue']]
# grouped_bar_plot_vector[['Cocoa.origin']][['Search.Type']]
# grouped_bar_plot_vector[['Cocoa.level']][['Has.chocolate']]
# grouped_bar_plot_vector[['Cocoa.level']][['Brand']]
# grouped_bar_plot_vector[['Cocoa.level']][['Cocoa.origin']]
# grouped_bar_plot_vector[['Cocoa.level']][['Types']]
# grouped_bar_plot_vector[['Cocoa.level']][['Variety']]
# grouped_bar_plot_vector[['Cocoa.level']][['Venue']]
# grouped_bar_plot_vector[['Cocoa.level']][['Search.Type']]
# grouped_bar_plot_vector[['Types']][['Has.chocolate']]
# grouped_bar_plot_vector[['Types']][['Brand']]
# grouped_bar_plot_vector[['Types']][['Cocoa.origin']]
# grouped_bar_plot_vector[['Types']][['Cocoa.level']]
# grouped_bar_plot_vector[['Types']][['Variety']]
# grouped_bar_plot_vector[['Types']][['Venue']]
# grouped_bar_plot_vector[['Types']][['Search.Type']]
# grouped_bar_plot_vector[['Variety']][['Has.chocolate']]
# grouped_bar_plot_vector[['Variety']][['Brand']]
# grouped_bar_plot_vector[['Variety']][['Cocoa.origin']]
# grouped_bar_plot_vector[['Variety']][['Cocoa.level']]
# grouped_bar_plot_vector[['Variety']][['Types']]
# grouped_bar_plot_vector[['Variety']][['Venue']]
# grouped_bar_plot_vector[['Variety']][['Search.Type']]
# grouped_bar_plot_vector[['Venue']][['Has.chocolate']]
# grouped_bar_plot_vector[['Venue']][['Brand']]
# grouped_bar_plot_vector[['Venue']][['Cocoa.origin']]
# grouped_bar_plot_vector[['Venue']][['Cocoa.level']]
# grouped_bar_plot_vector[['Venue']][['Types']]
# grouped_bar_plot_vector[['Venue']][['Variety']]
# grouped_bar_plot_vector[['Venue']][['Search.Type']]
# grouped_bar_plot_vector[['Search.Type']][['Has.chocolate']]
# grouped_bar_plot_vector[['Search.Type']][['Brand']]
# grouped_bar_plot_vector[['Search.Type']][['Cocoa.origin']]
# grouped_bar_plot_vector[['Search.Type']][['Cocoa.level']]
# grouped_bar_plot_vector[['Search.Type']][['Types']]
# grouped_bar_plot_vector[['Search.Type']][['Variety']]
# grouped_bar_plot_vector[['Search.Type']][['Venue']]

# Bubble Charts~Comparative stats(Nominal variables)
# bubble_chart_vector[['Has.chocolate']][['Brand']]
# bubble_chart_vector[['Has.chocolate']][['Cocoa.origin']]
# bubble_chart_vector[['Has.chocolate']][['Cocoa.level']]
# bubble_chart_vector[['Has.chocolate']][['Types']]
# bubble_chart_vector[['Has.chocolate']][['Variety']]
# bubble_chart_vector[['Has.chocolate']][['Venue']]
# bubble_chart_vector[['Has.chocolate']][['Search.Type']]
# bubble_chart_vector[['Brand']][['Has.chocolate']]
# bubble_chart_vector[['Brand']][['Cocoa.origin']]
# bubble_chart_vector[['Brand']][['Cocoa.level']]
# bubble_chart_vector[['Brand']][['Types']]
# bubble_chart_vector[['Brand']][['Variety']]
# bubble_chart_vector[['Brand']][['Venue']]
# bubble_chart_vector[['Brand']][['Search.Type']]
# bubble_chart_vector[['Cocoa.origin']][['Has.chocolate']]
# bubble_chart_vector[['Cocoa.origin']][['Brand']]
# bubble_chart_vector[['Cocoa.origin']][['Cocoa.level']]
# bubble_chart_vector[['Cocoa.origin']][['Types']]
# bubble_chart_vector[['Cocoa.origin']][['Variety']]
# bubble_chart_vector[['Cocoa.origin']][['Venue']]
# bubble_chart_vector[['Cocoa.origin']][['Search.Type']]
# bubble_chart_vector[['Cocoa.level']][['Has.chocolate']]
# bubble_chart_vector[['Cocoa.level']][['Brand']]
# bubble_chart_vector[['Cocoa.level']][['Cocoa.origin']]
# bubble_chart_vector[['Cocoa.level']][['Types']]
# bubble_chart_vector[['Cocoa.level']][['Variety']]
# bubble_chart_vector[['Cocoa.level']][['Venue']]
# bubble_chart_vector[['Cocoa.level']][['Search.Type']]
# bubble_chart_vector[['Types']][['Has.chocolate']]
# bubble_chart_vector[['Types']][['Brand']]
# bubble_chart_vector[['Types']][['Cocoa.origin']]
# bubble_chart_vector[['Types']][['Cocoa.level']]
# bubble_chart_vector[['Types']][['Variety']]
# bubble_chart_vector[['Types']][['Venue']]
# bubble_chart_vector[['Types']][['Search.Type']]
# bubble_chart_vector[['Variety']][['Has.chocolate']]
# bubble_chart_vector[['Variety']][['Brand']]
# bubble_chart_vector[['Variety']][['Cocoa.origin']]
# bubble_chart_vector[['Variety']][['Cocoa.level']]
# bubble_chart_vector[['Variety']][['Types']]
# bubble_chart_vector[['Variety']][['Venue']]
# bubble_chart_vector[['Variety']][['Search.Type']]
# bubble_chart_vector[['Venue']][['Has.chocolate']]
# bubble_chart_vector[['Venue']][['Brand']]
# bubble_chart_vector[['Venue']][['Cocoa.origin']]
# bubble_chart_vector[['Venue']][['Cocoa.level']]
# bubble_chart_vector[['Venue']][['Types']]
# bubble_chart_vector[['Venue']][['Variety']]
# bubble_chart_vector[['Venue']][['Search.Type']]
# bubble_chart_vector[['Search.Type']][['Has.chocolate']]
# bubble_chart_vector[['Search.Type']][['Brand']]
# bubble_chart_vector[['Search.Type']][['Cocoa.origin']]
# bubble_chart_vector[['Search.Type']][['Cocoa.level']]
# bubble_chart_vector[['Search.Type']][['Types']]
# bubble_chart_vector[['Search.Type']][['Variety']]
# bubble_chart_vector[['Search.Type']][['Venue']]

# Fisher's Exact Test~Comparative stats(Nominal variables)
# fisher_exact_test_vector[['Has.chocolate']][['Brand']]
# fisher_exact_test_vector[['Has.chocolate']][['Cocoa.origin']]
# fisher_exact_test_vector[['Has.chocolate']][['Cocoa.level']]
# fisher_exact_test_vector[['Has.chocolate']][['Types']]
# fisher_exact_test_vector[['Has.chocolate']][['Variety']]
# fisher_exact_test_vector[['Has.chocolate']][['Venue']]
# fisher_exact_test_vector[['Has.chocolate']][['Search.Type']]
# fisher_exact_test_vector[['Brand']][['Has.chocolate']]
# fisher_exact_test_vector[['Brand']][['Cocoa.origin']]
# fisher_exact_test_vector[['Brand']][['Cocoa.level']]
# fisher_exact_test_vector[['Brand']][['Types']]
# fisher_exact_test_vector[['Brand']][['Variety']]
# fisher_exact_test_vector[['Brand']][['Venue']]
# fisher_exact_test_vector[['Brand']][['Search.Type']]
# fisher_exact_test_vector[['Cocoa.origin']][['Has.chocolate']]
# fisher_exact_test_vector[['Cocoa.origin']][['Brand']]
# fisher_exact_test_vector[['Cocoa.origin']][['Cocoa.level']]
# fisher_exact_test_vector[['Cocoa.origin']][['Types']]
# fisher_exact_test_vector[['Cocoa.origin']][['Variety']]
# fisher_exact_test_vector[['Cocoa.origin']][['Venue']]
# fisher_exact_test_vector[['Cocoa.origin']][['Search.Type']]
# fisher_exact_test_vector[['Cocoa.level']][['Has.chocolate']]
# fisher_exact_test_vector[['Cocoa.level']][['Brand']]
# fisher_exact_test_vector[['Cocoa.level']][['Cocoa.origin']]
# fisher_exact_test_vector[['Cocoa.level']][['Types']]
# fisher_exact_test_vector[['Cocoa.level']][['Variety']]
# fisher_exact_test_vector[['Cocoa.level']][['Venue']]
# fisher_exact_test_vector[['Cocoa.level']][['Search.Type']]
# fisher_exact_test_vector[['Types']][['Has.chocolate']]
# fisher_exact_test_vector[['Types']][['Brand']]
# fisher_exact_test_vector[['Types']][['Cocoa.origin']]
# fisher_exact_test_vector[['Types']][['Cocoa.level']]
# fisher_exact_test_vector[['Types']][['Variety']]
# fisher_exact_test_vector[['Types']][['Venue']]
# fisher_exact_test_vector[['Types']][['Search.Type']]
# fisher_exact_test_vector[['Variety']][['Has.chocolate']]
# fisher_exact_test_vector[['Variety']][['Brand']]
# fisher_exact_test_vector[['Variety']][['Cocoa.origin']]
# fisher_exact_test_vector[['Variety']][['Cocoa.level']]
# fisher_exact_test_vector[['Variety']][['Types']]
# fisher_exact_test_vector[['Variety']][['Venue']]
# fisher_exact_test_vector[['Variety']][['Search.Type']]
# fisher_exact_test_vector[['Venue']][['Has.chocolate']]
# fisher_exact_test_vector[['Venue']][['Brand']]
# fisher_exact_test_vector[['Venue']][['Cocoa.origin']]
# fisher_exact_test_vector[['Venue']][['Cocoa.level']]
# fisher_exact_test_vector[['Venue']][['Types']]
# fisher_exact_test_vector[['Venue']][['Variety']]
# fisher_exact_test_vector[['Venue']][['Search.Type']]
# fisher_exact_test_vector[['Search.Type']][['Has.chocolate']]
# fisher_exact_test_vector[['Search.Type']][['Brand']]
# fisher_exact_test_vector[['Search.Type']][['Cocoa.origin']]
# fisher_exact_test_vector[['Search.Type']][['Cocoa.level']]
# fisher_exact_test_vector[['Search.Type']][['Types']]
# fisher_exact_test_vector[['Search.Type']][['Variety']]
# fisher_exact_test_vector[['Search.Type']][['Venue']]

# Shapiro Wilk's Correlation Test~Comparative stats(Continuous variables)
# shapiro_wilk_test_vector[['Temperature']]
# shapiro_wilk_test_vector[['Year']]
# shapiro_wilk_test_vector[['Number.of.citations']]
# shapiro_wilk_test_vector[['Publication.year']]

# Pearson's Correlation Test~Comparative stats(Continuous variables)
# pearson_cor_test_vector[['Temperature']][['Year']]
# pearson_cor_test_vector[['Temperature']][['Number.of.citations']]
# pearson_cor_test_vector[['Temperature']][['Publication.year']]
# pearson_cor_test_vector[['Year']][['Temperature']]
# pearson_cor_test_vector[['Year']][['Number.of.citations']]
# pearson_cor_test_vector[['Year']][['Publication.year']]
# pearson_cor_test_vector[['Number.of.citations']][['Temperature']]
# pearson_cor_test_vector[['Number.of.citations']][['Year']]
# pearson_cor_test_vector[['Number.of.citations']][['Publication.year']]
# pearson_cor_test_vector[['Publication.year']][['Temperature']]
# pearson_cor_test_vector[['Publication.year']][['Year']]
# pearson_cor_test_vector[['Publication.year']][['Number.of.citations']]

# Spearman's Correlation Test~Comparative stats(Continuous variables)
# spearman_cor_test_vector[['Temperature']][['Year']]
# spearman_cor_test_vector[['Temperature']][['Number.of.citations']]
# spearman_cor_test_vector[['Temperature']][['Publication.year']]
# spearman_cor_test_vector[['Year']][['Temperature']]
# spearman_cor_test_vector[['Year']][['Number.of.citations']]
# spearman_cor_test_vector[['Year']][['Publication.year']]
# spearman_cor_test_vector[['Number.of.citations']][['Temperature']]
# spearman_cor_test_vector[['Number.of.citations']][['Year']]
# spearman_cor_test_vector[['Number.of.citations']][['Publication.year']]
# spearman_cor_test_vector[['Publication.year']][['Temperature']]
# spearman_cor_test_vector[['Publication.year']][['Year']]
# spearman_cor_test_vector[['Publication.year']][['Number.of.citations']]

#######################################################################################